services:
  web:
    container_name: estacionaboa-web
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4500:80"
    volumes:
      - ./www:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - db
    environment:
      TZ: America/Fortaleza
    networks:
      - codeigniter

  db:
    container_name: estacionaboa-db
    image: mysql:8.0
    command: ['--default-authentication-plugin=mysql_native_password', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_general_ci']
    restart: always
    environment:
      MYSQL_DATABASE: estacionaboa
      MYSQL_ROOT_PASSWORD: jotahdev
    volumes:
      - codeigniter_mysql_data:/var/lib/mysql
      - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    networks:
      - codeigniter
    ports:
      - "3306:3306"

  phpmyadmin:
    container_name: estacionaboa-phpmyadmin
    build:
      context: .
      dockerfile: Dockerfile.phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: sextafeira
    ports:
      - "8080:80"
    networks:
      - codeigniter

volumes:
  codeigniter_mysql_data:

networks:
  codeigniter:
    driver: bridge
